name:                roo-lang
version:             0.1.0.0
license:             BSD3
author:              "Ben Frengley"
maintainer:          "bfrengley@student.unimelb.edu.au"
copyright:           "2020 Ben Frengley"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitLab at <https://gitlab.unimelb.edu.au/sjwebb/pli-project-1#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- text
- containers
- mtl

library:
  source-dirs: src

executables:
  Roo:
    main:                Roo.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - roo-lang
    - pretty-simple

tests:
  roo-lang-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - roo-lang
    - hspec
    - paths
